name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain manually
      run: |
        sudo apt update && sudo apt install rustc
        rustup component add rustfmt clippy

    - name: Add Rust to PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Check formatting
      run: cargo fmt --check

    - name: Lint with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run tests with all features
      run: cargo test --all-features --verbose
